### ISSUE TITLE
DirectHW/DirectHW.h not found

### ISSUE THREAD

**Issue by mangomangomango0820** [vampirecat35/pciutils-osx#2]
I am working with macOS 11.4 and trying to make pciutils according to your read.md,

```shell
xueshanzhang@XUESHANs-MacBook-Pro pciutils-osx-master % make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C lib all
gcc -O2 -F/Library/Frameworks -Wall -W -Wno-parentheses -Wstrict-prototypes -Wmissing-prototypes   -c -o i386-ports.o i386-ports.c
In file included from i386-ports.c:18:
./i386-io-darwin.h:19:10: fatal error: 'DirectHW/DirectHW.h' file not found
#include <DirectHW/DirectHW.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [i386-ports.o] Error 1
make: *** [lib/libpci.a] Error 2
```

this is what I got while making pciutils.

this page (https://www.insanelymac.com/forum/topic/346408-hwtools-for-mavericks-and-better-directhw-for-macos-big-sur-superiotool-mptable-osxpmem-iwleeprom-ectool-msrtool-ifdtool-inteltool-nvramtool-pciutils-370-and-flashrom-12/) directed me to https://github.com/vampirecat35/DirectHW-BigSur,
however I came across another issue, referring to https://github.com/vampirecat35/DirectHW-BigSur/issues/1
